BOT_TOKEN = "5357825309:AAGZaf1vmGgJvd8vJuIWR22KVGIFh5jokEk"
APPNAME = "hdmovie5"
WEBHOOK_HOST = f"https://{APPNAME}.herokuapp.com/"
WEBHOOK_PATH = f"/{BOT_TOKEN}/"
WEBHOOK_URL = f"{WEBHOOK_HOST}{WEBHOOK_PATH}"
WEBAPP_HOST = "0.0.0.0"
WEBAPP_PORT = 8000
